version: "3.8"

services:
  tta-bot-dev:
    build: .
    container_name: tta-bot-dev
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - ADMIN_ID=${ADMIN_ID}
      - PORT=8080
    env_file:
      - .env
    volumes:
      # Монтируем код для разработки (hot reload)
      - .:/app
      - /app/__pycache__
    command:
      ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080", "--reload"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge
